# Generated by Django 5.0.3 on 2024-03-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('table_number', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
